---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"
  tags: kubelet

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true
  tags: kubelet

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true
  tags: kubelet

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/kubernetes" }
    - { dest: "/etc/kubernetes/manifests" }
    - { dest: "/lib/systemd/system" }
    - { dest: "/lib/systemd/system/kubelet.service.d" }
    - { dest: "/usr/local/bin" }
    - { dest: "/var/lib/kubelet" }
    - { dest: "{{ kubelet_download.dest | dirname }}" }
  tags: kubelet

- name: download archive
  vars:
    ansible_python_interpreter: "python3"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    mode: "{{ item.mode | default('0644') }}"
    timeout: 300
  loop:
    - "{{ kubelet_download }}"
  register: get_url_result
  until: get_url_result is succeeded
  tags: kubelet

- name: unarchive package
  shell: |
    set -o pipefail
    cd /usr/local/bin
    TMP_DIR="$(mktemp -d)" \
      && cp {{ kubelet_download.dest }} $TMP_DIR/kubelet \
      && chown root:root $TMP_DIR/kubelet \
      && chmod 0755 $TMP_DIR/kubelet \
      && mv $TMP_DIR/kubelet . \
      && rm -rf $TMP_DIR
  args:
    executable: "/bin/bash"
  when: get_url_result is changed
  notify:
    - kubelet | systemctl restart kubelet.service
  tags: kubelet

- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/lib/systemd/system/kubelet-shutdown.service" }
    - { dest: "/lib/systemd/system/kubelet.service" }
  notify:
    - kubelet | systemctl daemon-reload
    - kubelet | systemctl restart kubelet.service
  tags: kubelet

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/systemd/system/kubelet.service", state: "absent" }
    - { dest: "/lib/systemd/system/kubelet-shutdown.service" }
    - { dest: "/lib/systemd/system/kubelet.service" }
    - { dest: "/usr/local/bin/kubelet", mode: "0755" }
  tags: kubelet

- name: systemctl start kubelet.service
  service:
    name: "kubelet.service"
    state: "started"
    enabled: true
  changed_when: false
  ignore_errors: true
  tags: kubelet

- name: systemctl start kubelet-shutdown.service
  service:
    name: "kubelet-shutdown.service"
    state: "started"
    enabled: true
  changed_when: false
  ignore_errors: true
  tags: kubelet

- name: flush handlers
  meta: flush_handlers
  tags: kubelet
